# -*- coding: utf-8 -*-
"""IIT2018131_A3_Decryption.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mJ3-vRHjOV6QqtEP6vWNKfT00hq3Fl5_
"""

import math
import random

def decryption(private_key,message,block_size):
  d,n = private_key
  eBlocks = message.split(',')
  decrypted_message = ''
  for i in eBlocks:
    i = int(i)
    i = (i**d)%n
    block = ''
    for j in range(block_size):
      block = chr(i%1000)+block
      i //= 1000
    decrypted_message += block
   
  return decrypted_message

print("RSA Decryption")
file_name = input("Enter the file name where private key is stored: ")
fo = open(file_name, 'r')
n = int(fo.readline())
d = int(fo.readline())
fo.close()

private_key = (d,n)
print("private key = ",private_key)

message = input("Enter comma separated message to decrypt: ")
block_size = int(input("Enter block size: "))
print("Decrypting......")
print("Decrypted message is: ",decryption(private_key,message,block_size))

